name: persistent_homology_play_env
channels:
  - conda-forge
  - defaults
dependencies:
  - dionysus>=2.0.7
  - jupyter>=1.0.0
  - mkl-service>=2.3.0
  - numpy>=1.19.1
  - python>=3.8.5
  - ripser>=0.5.3
  - scikit-learn>=0.23.2
  - seaborn=>0.11.0

